import { Categories, Product } from '../types/product';

// Generate a random ID
const generateId = () => Math.random().toString(36).substring(2, 11);

// Generate a random date in the past year
const generateDate = () => {
  const date = new Date();
  date.setDate(date.getDate() - Math.floor(Math.random() * 365));
  return date.toISOString();
};

// Generate mock product data
export const mockProducts: Product[] = [
  {
    id: generateId(),
    name: 'iPhone 15 Pro',
    category: Categories.Electronics,
    price: 999.99,
    stock: 25,
    description: 'Latest Apple iPhone with advanced features',
    image: 'https://images.pexels.com/photos/1647976/pexels-photo-1647976.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'Samsung Galaxy S23',
    category: Categories.Electronics,
    price: 899.99,
    stock: 30,
    description: 'Latest Samsung flagship phone',
    image: 'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'Nike Air Max',
    category: Categories.Clothing,
    price: 129.99,
    stock: 45,
    description: 'Comfortable running shoes',
    image: 'https://images.pexels.com/photos/1598508/pexels-photo-1598508.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'Levi\'s 501 Jeans',
    category: Categories.Clothing,
    price: 59.99,
    stock: 60,
    description: 'Classic denim jeans',
    image: 'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'Organic Quinoa',
    category: Categories.Food,
    price: 8.99,
    stock: 8,
    description: 'Healthy grain alternative',
    image: 'https://images.pexels.com/photos/7421242/pexels-photo-7421242.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'Dark Chocolate',
    category: Categories.Food,
    price: 4.99,
    stock: 100,
    description: '72% Cocoa Premium Chocolate',
    image: 'https://images.pexels.com/photos/65882/chocolate-dark-coffee-confiserie-65882.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'Mid-Century Sofa',
    category: Categories.Furniture,
    price: 799.99,
    stock: 5,
    description: 'Elegant living room furniture',
    image: 'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'Bookshelf',
    category: Categories.Furniture,
    price: 149.99,
    stock: 12,
    description: 'Wooden bookshelf with 5 shelves',
    image: 'https://images.pexels.com/photos/696407/pexels-photo-696407.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'The Great Gatsby',
    category: Categories.Books,
    price: 12.99,
    stock: 30,
    description: 'Classic novel by F. Scott Fitzgerald',
    image: 'https://images.pexels.com/photos/1770770/pexels-photo-1770770.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'LEGO Star Wars Set',
    category: Categories.Toys,
    price: 89.99,
    stock: 18,
    description: 'Building set for ages 9+',
    image: 'https://images.pexels.com/photos/1767434/pexels-photo-1767434.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'Dumbbell Set',
    category: Categories.Other,
    price: 199.99,
    stock: 7,
    description: 'Adjustable weight set for home gym',
    image: 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'Wireless Headphones',
    category: Categories.Electronics,
    price: 159.99,
    stock: 35,
    description: 'Noise cancelling over-ear headphones',
    image: 'https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'Smart Watch',
    category: Categories.Electronics,
    price: 249.99,
    stock: 22,
    description: 'Fitness and health tracking smartwatch',
    image: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'Cotton T-Shirt',
    category: Categories.Clothing,
    price: 19.99,
    stock: 80,
    description: 'Comfortable casual t-shirt',
    image: 'https://images.pexels.com/photos/428340/pexels-photo-428340.jpeg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
  {
    id: generateId(),
    name: 'Extra Virgin Olive Oil',
    category: Categories.Food,
    price: 15.99,
    stock: 40,
    description: 'Premium cooking oil from Italy',
    image: 'https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking.jpg?auto=compress&cs=tinysrgb&w=300',
    createdAt: generateDate(),
    updatedAt: generateDate(),
  },
];